#pragma once


namespace bsp_tool::respawn_entertainment::titanfall {
    const int BSP_VERSION = 29;
    namespace LUMP {
        const int ENTITIES                  = 0x00,  UNUSED_64                           = 0x40,
                  PLANES                    = 0x01,  UNUSED_65                           = 0x41,
                  TEXTURE_DATA              = 0x02,  TRICOLL_TRIS                        = 0x42,
                  VERTICES                  = 0x03,  UNUSED_67                           = 0x43,
                  UNUSED_04                 = 0x04,  TRICOLL_NODES                       = 0x44,
                  UNUSED_05                 = 0x05,  TRICOLL_HEADERS                     = 0x45,
                  UNUSED_06                 = 0x06,  PHYSICS_TRIANGLES                   = 0x46,
                  UNUSED_07                 = 0x07,  VERTEX_UNLIT                        = 0x47,
                  UNUSED_08                 = 0x08,  VERTEX_LIT_FLAT                     = 0x48,
                  UNUSED_09                 = 0x09,  VERTEX_LIT_BUMP                     = 0x49,
                  UNUSED_10                 = 0x0A,  VERTEX_UNLIT_TS                     = 0x4A,
                  UNUSED_11                 = 0x0B,  VERTEX_RESERVED_4                   = 0x4B,
                  UNUSED_12                 = 0x0C,  VERTEX_RESERVED_5                   = 0x4C,
                  UNUSED_13                 = 0x0D,  VERTEX_RESERVED_6                   = 0x4D,
                  MODELS                    = 0x0E,  VERTEX_RESERVED_7                   = 0x4E,
                  UNUSED_15                 = 0x0F,  MESH_INDICES                        = 0x4F,
                  UNUSED_16                 = 0x10,  MESHES                              = 0x50,
                  UNUSED_17                 = 0x11,  MESH_BOUNDS                         = 0x51,
                  UNUSED_18                 = 0x12,  MATERIAL_SORT                       = 0x52,
                  UNUSED_19                 = 0x13,  LIGHTMAP_HEADERS                    = 0x53,
                  UNUSED_20                 = 0x14,  LIGHTMAP_DATA_DXT5                  = 0x54,
                  UNUSED_21                 = 0x15,  CM_GRID                             = 0x55,
                  UNUSED_22                 = 0x16,  CM_GRID_CELLS                       = 0x56,
                  UNUSED_23                 = 0x17,  CM_GEO_SETS                         = 0x57,
                  ENTITY_PARTITIONS         = 0x18,  CM_GEO_SET_BOUNDS                   = 0x58,
                  UNUSED_25                 = 0x19,  CM_PRIMITIVES                       = 0x59,
                  UNUSED_26                 = 0x1A,  CM_PRIMITIVE_BOUNDS                 = 0x5A,
                  UNUSED_27                 = 0x1B,  CM_UNIQUE_CONTENTS                  = 0x5B,
                  UNUSED_28                 = 0x1C,  CM_BRUSHES                          = 0x5C,
                  PHYSICS_COLLIDE           = 0x1D,  CM_BRUSH_SIDE_PLANE_OFFSETS         = 0x5D,
                  VERTEX_NORMALS            = 0x1E,  CM_BRUSH_SIDE_PROPS                 = 0x5E,
                  UNUSED_31                 = 0x1F,  CM_BRUSH_TEX_VECS                   = 0x5F,
                  UNUSED_32                 = 0x20,  TRICOLL_BEVEL_STARTS                = 0x60,
                  UNUSED_33                 = 0x21,  TRICOLL_BEVEL_INDICES               = 0x61,
                  UNUSED_34                 = 0x22,  LIGHTMAP_DATA_SKY                   = 0x62,
                  GAME_LUMP                 = 0x23,  CSM_AABB_NODES                      = 0x63,
                  LEAF_WATER_DATA           = 0x24,  CSM_OBJ_REFERENCES                  = 0x64,
                  UNUSED_37                 = 0x25,  LIGHTPROBES                         = 0x65,
                  UNUSED_38                 = 0x26,  STATIC_PROP_LIGHTPROBE_INDICES      = 0x66,
                  UNUSED_39                 = 0x27,  LIGHTPROBE_TREE                     = 0x67,
                  PAKFILE                   = 0x28,  LIGHTPROBE_REFERENCES               = 0x68,
                  UNUSED_41                 = 0x29,  LIGHTMAP_DATA_REAL_TIME_LIGHTS      = 0x69,
                  CUBEMAPS                  = 0x2A,  CELL_BSP_NODES                      = 0x6A,
                  TEXTURE_DATA_STRING_DATA  = 0x2B,  CELLS                               = 0x6B,
                  TEXTURE_DATA_STRING_TABLE = 0x2C,  PORTALS                             = 0x6C,
                  UNUSED_45                 = 0x2D,  PORTAL_VERTICES                     = 0x6D,
                  UNUSED_46                 = 0x2E,  PORTAL_EDGES                        = 0x6E,
                  UNUSED_47                 = 0x2F,  PORTAL_VERTEX_EDGES                 = 0x6F,
                  UNUSED_48                 = 0x30,  PORTAL_VERTEX_REFERENCES            = 0x70,
                  UNUSED_49                 = 0x31,  PORTAL_EDGE_REFERENCES              = 0x71,
                  UNUSED_50                 = 0x32,  PORTAL_EDGE_INTERSECT_EDGE          = 0x72,
                  UNUSED_51                 = 0x33,  PORTAL_EDGE_INTERSECT_AT_VERTEX     = 0x73,
                  UNUSED_52                 = 0x34,  PORTAL_EDGE_INTERSECT_HEADER        = 0x74,
                  UNUSED_53                 = 0x35,  OCCLUSION_MESH_VERTICES             = 0x75,
                  WORLD_LIGHTS              = 0x36,  OCCLUSION_MESH_INDICES              = 0x76,
                  WORLDLIGHT_PARENT_INFO    = 0x37,  CELL_AABB_NODES                     = 0x77,
                  UNUSED_56                 = 0x38,  OBJ_REFERENCES                      = 0x78,
                  UNUSED_57                 = 0x39,  OBJ_REFERENCE_BOUNDS                = 0x79,
                  UNUSED_58                 = 0x3A,  LIGHTMAP_DATA_REAL_TIME_LIGHTS_PAGE = 0x7A,
                  UNUSED_59                 = 0x3B,  LEVEL_INFO                          = 0x7B,
                  UNUSED_60                 = 0x3C,  SHADOW_MESH_OPAQUE_VERTICES         = 0x7C,
                  UNUSED_61                 = 0x3D,  SHADOW_MESH_ALPHA_VERTICES          = 0x7D,
                  PHYSICS_LEVEL             = 0x3E,  SHADOW_MESH_INDICES                 = 0x7E,
                  UNUSED_63                 = 0x3F,  SHADOW_MESH_MESHES                  = 0x7F;
    }
}

