-- Generated via python script
INSERT INTO Game(name) VALUES
	('Alien Swarm'),
	('Alien Swarm: Reactive Drop'),
	('Alkaline'),
	("American McGee's Alice"),
	('Amsterdoom'),
	('Anachronox'),
	('Apex Legends'),
	('Apex Legends: Season 0 - Preseason'),
	('Apex Legends: Season 1 - Wild Frontier'),
	('Apex Legends: Season 2 - Battle Charge'),
	('Apex Legends: Season 3 - Meltdown'),
	('Apex Legends: Season 4 - Assimilation'),
	("Apex Legends: Season 5 - Fortune's Favour"),
	('Apex Legends: Season 6 - Boosted'),
	('Apex Legends: Season 7 - Ascension'),
	('Apex Legends: Season 8 - Mayhem'),
	('Apex Legends: Season 9 - Legacy'),
	('Apex Legends: Season 10 - Emergence'),
	('Apex Legends: Season 11 - Escape'),
	('Apex Legends: Season 12 - Defiance'),
	('Apex Legends: Season 13 - Saviours'),
	('Apex Legends: Season 14 - Hunted'),
	('Apex Legends: Season 15 - Eclipse'),
	('Apex Legends: Season 16 - Revelry'),
	('Apex Legends: Season 17 - Arsenal'),
	('Apex Legends: Season 18 - Resurrection'),
	('Apex Legends: Season 19 - Ignite'),
	('Apex Legends: Season 20 - Breakout'),
	('Apex Legends: Season 21 - Upheaval'),
	('Black Mesa'),
	('Blade Symphony'),
	('Bloody Good Time'),
	('Call of Duty'),
	('Call of Duty: Burnville Demo'),
	('Call of Duty: Dawnville Demo'),
	('Call of Duty 2'),
	('Call of Duty 4: Modern Warfare'),
	('Call of Duty: Black Ops III'),
	('Call of Duty: United Offensive'),
	('Call of Duty: World at War'),
	('Cocaine Diesel'),
	('Contagion'),
	('Counter-Strike'),
	('Counter-Strike: Condition Zero'),
	('Counter-Strike: Condition Zero - Deleted Scenes'),
	('Counter-Strike: Global Offensive'),
	('Counter-Strike: Online 2'),
	('Counter-Strike: Source'),
	('Cry of Fear'),
	('D-Day Normandy'),
	('Daikatana'),
	('Dark Messiah of Might & Magic Multi-Player'),
	('Dark Messiah of Might & Magic Singleplayer'),
	('DarkPlaces'),
	('Day of Defeat'),
	('Day of Defeat: Source'),
	('Deathmatch Classic'),
	('Dino D-Day'),
	('Double Action: Boogaloo'),
	('E.Y.E: Divine Cybermancy'),
	('Entropy: Zero 2'),
	('Fistful of Frags'),
	('Fortress Forever'),
	('G-String'),
	("Garry's Mod"),
	('Half-Life'),
	('Half-Life 2'),
	('Half-Life 2 VR Mod'),
	('Half-Life 2: Deathmatch'),
	('Half-Life 2: Episode 1'),
	('Half-Life 2: Episode 2'),
	('Half-Life 2: Lost Coast'),
	('Half-Life Deathmatch: Source'),
	('Half-Life: Blue Shift'),
	('Half-Life: Opposing Force'),
	('Half-Life: Source'),
	('Halfquake Trilogy'),
	('Heavy Metal F.A.K.K. 2'),
	('Heretic II'),
	('Hexen II'),
	('INFRA'),
	('James Bond 007: Nightfire'),
	('Kingpin: Life of Crime'),
	('Left 4 Dead'),
	('Left 4 Dead 2'),
	('Medal of Honor: Allied Assault'),
	('Medal of Honor: Allied Assault (Demo)'),
	('Medal of Honor: Allied Assault - Breakthrough'),
	('Medal of Honor: Allied Assault - Spearhead'),
	('Momentum Mod Playtest'),
	('NEOTOKYO'),
	('Natural Selection'),
	('Nexuiz Classic'),
	('Nexuiz'),
	('No More Room in Hell'),
	('Paranoia'),
	('Portal'),
	('Portal 2'),
	('Quake'),
	('Quake 4'),
	('Quake 64'),
	('Quake Champions'),
	('Quake II'),
	('Quake III Arena'),
	('Quake III: Team Arena'),
	('Quake Live'),
	('Quake: Dimension of the Past'),
	('Return to Castle Wolfenstein'),
	('Richochet'),
	('SiN'),
	('SiN Episodes: Emergence'),
	('SiN: Gold'),
	('Soldier of Fortune'),
	('Soldier of Fortune II: Double Helix'),
	('Source Filmmaker'),
	('Source SDK 2013'),
	('Star Trek: Elite Force II'),
	('Star Trek: Voyager - Elite Force'),
	('Star Wars: Jedi Knight - Jedi Academy'),
	('Star Wars: Jedi Knight II - Jedi Outcast'),
	('Sven Co-op'),
	('Synergy'),
	('Tactical Intervention'),
	('Team Fortress 2'),
	('Team Fortress Classic'),
	('Team Fortress Quake'),
	("The Beginner's Guide"),
	('The Orange Box'),
	('The Ship'),
	('The Stanley Parable'),
	('Titanfall'),
	('Titanfall (Beta)'),
	('Titanfall 2'),
	('Titanfall 2 (Demo)'),
	('Titanfall 2 (Tech Test)'),
	('Titanfall: Online'),
	('Vampire: The Masquerade - Bloodlines'),
	('Vindictus'),
	('WRATH: Aeon of Ruin'),
	('Warfork'),
	('Warsow'),
	('Wolfenstein: Enemy Territory'),
	('Xonotic'),
	('Zeno Clash'),
	('Zeno Clash (Demo)'),
	('メルヘソバスターズ [Fairy Tale Busters]');


INSERT INTO Relation(name) VALUES
	('Beta'),
	('Bundle'),
	('Demo'),
	('Engine'),
	('Expansion'),
	('Fork'),
	('Non-GPL Rebuild'),
	('Season'),
	('Sequel');


INSERT INTO GameRelation(parent, child, relation) VALUES
	(7,8,8),
	(7,9,8),
	(7,10,8),
	(7,11,8),
	(7,12,8),
	(7,13,8),
	(7,14,8),
	(7,15,8),
	(7,16,8),
	(7,17,8),
	(7,18,8),
	(7,19,8),
	(7,20,8),
	(7,21,8),
	(7,22,8),
	(7,23,8),
	(7,24,8),
	(7,25,8),
	(7,26,8),
	(7,27,8),
	(7,28,8),
	(7,29,8),
	(33,34,3),
	(33,35,3),
	(33,36,9),
	(36,37,9),
	(66,74,5),
	(66,75,5),
	(66,67,9),
	(67,70,9),
	(70,71,9),
	(97,98,9),
	(100,103,2),
	(128,67,2),
	(128,70,2),
	(128,71,2),
	(128,97,2),
	(128,124,2),
	(131,132,1),
	(131,133,9),
	(133,135,1),
	(141,140,6),
	(140,41,6),
	(54,93,4),
	(93,143,6),
	(93,94,7);


INSERT INTO Series(name) VALUES
	('Alien Swarm'),
	('Call of Duty'),
	('Counter-Strike'),
	('Half-Life'),
	('Heretic'),
	('Medal of Honor'),
	('Might and Magic'),
	('Quake'),
	('SiN'),
	('Soldier of Fortune'),
	('Team Fortress'),
	('Titanfall'),
	('Wolfenstein');


INSERT INTO GameSeries(game, series) VALUES
	(1,1),
	(1,2),
	(2,33),
	(2,36),
	(2,37),
	(2,38),
	(2,39),
	(2,40),
	(3,43),
	(3,44),
	(3,45),
	(3,46),
	(3,47),
	(3,48),
	(4,67),
	(4,69),
	(4,70),
	(4,71),
	(4,72),
	(4,73),
	(4,66),
	(4,74),
	(4,75),
	(4,76),
	(5,79),
	(5,80),
	(6,86),
	(6,87),
	(6,88),
	(6,89),
	(7,52),
	(7,53),
	(8,99),
	(8,101),
	(8,102),
	(8,103),
	(8,104),
	(8,105),
	(8,106),
	(8,107),
	(9,110),
	(9,111),
	(9,112),
	(10,113),
	(10,114),
	(11,124),
	(11,125),
	(11,126),
	(12,7),
	(12,131),
	(12,132),
	(12,133),
	(12,134),
	(12,135),
	(12,136),
	(13,142);


