# SOURCE ENGINE TOOLS
STEAM_COMMON_DIR = D:/SteamLibrary/steamapps/common
# TODO: find games split across multiple steam directories
# TODO: point at game config etc, only need the compilers (vbsp, vvis, vrad & vbspinfo)
INFRA_BIN  = $(STEAM_COMMON_DIR)/INFRA/bin
ALIEN_BIN  = $(STEAM_COMMON_DIR)/Alien Swarm/bin
L4D_BIN    = $(STEAM_COMMON_DIR)/left 4 dead/bin
L4D2_BIN   = $(STEAM_COMMON_DIR)/Left 4 Dead 2/bin
TF2_BIN    = $(STEAM_COMMON_DIR)/Team Fortress 2/bin
HL2_BIN    = $(STEAM_COMMON_DIR)/half-life 2/bin

# EXTERNAL TOOLS
BSPFIX_LINK        = https://valvedev.info/tools/bspfix
COD1RADIANT_LINK   = https://moddb.com/downloads/cod-radiant
COD2RADIANT_LINK   = https://gamefront.com/games/call-of-duty-2/file/cod2-updated-map-mod-tool
COD4RADIANT_LINK   = https://github.com/promod/CoD4-Mod-Tools
CSO2CONVERTER_LINK = https://git.sr.ht/~leite/cso2-bsp-converter
GTKRADIANT_LINK    = https://github.com/TTimo/GtkRadiant
# GTK_RADIANT_GAMEPACK_LINK = https://svn.icculus.org/gtkradiant-gamepacks
# JBNTOOLS_LINK = https://code.google.com/archive/p/jbn-bsp-lump-tools
MAPBASE_LINK       = https://www.moddb.com/mods/mapbase/downloads/mapbase-release-build
TRENCHBROOM_LINK   = https://github.com/TrenchBroom/TrenchBroom
UBERTOOLS_LINK     = https://moddb.com/downloads/stef2-bertools-game-devolopment-kit

# TODO: "function" to check tool is installed; otherwise download & install
# -- make a toolsdir with symlinks to tools
# -- if link is absent, download & install it
TOOLSDIR := tools

# TODO: make symlinks to each toolkit
# -- install missing games w/ steamcmd? requires account with relevant games unlocked
# --- some games might require using a store / download link

# TODO: allow any valid tool choice for each branch

# TODO: locate / install tools; compile maps; build *info.txt files
